#!/usr/bin/env node
'use strict';
// Fleet credential provisioning — issue a UNIQUE ingest token per rig.
//
// Why: /ingest and the ETP endpoint authorise a batch against the rig's
// device_token, falling back to the fleet-wide INGEST_TOKEN. Running 50 rigs on
// that single shared fallback means any one compromised rig node can inject
// telemetry as any other rig, and rotating the shared token re-keys all 50 at
// once. This issues per-rig 256-bit tokens and emits the matching edge config
// fragment for each rig.
//
// Usage (inside the backend container, which already has PG* in its env):
//   docker compose exec crmf-backend node scripts/provision-rigs.js            # dry run
//   docker compose exec crmf-backend node scripts/provision-rigs.js --apply
//   docker compose exec crmf-backend node scripts/provision-rigs.js --apply --rotate
//   docker compose exec crmf-backend node scripts/provision-rigs.js --apply --rig AHWR-50-3
//   ... --out /data/rig-env                # write per-rig .env fragments
//
// Flags:
//   --apply          actually write tokens (default is a dry run)
//   --rotate         re-issue even for rigs that already have a token
//   --rig <id>       restrict to one rig (repeatable)
//   --out <dir>      write <rigId>.env fragments for the edge nodes
//   --central <url>  CENTRAL_URL to embed in the fragments

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { query } = require('../lib/db');

function parseArgs(argv) {
    const o = { apply: false, rotate: false, rigs: [], out: null, central: null, json: null };
    for (let i = 2; i < argv.length; i++) {
        const a = argv[i];
        if (a === '--apply') o.apply = true;
        else if (a === '--rotate') o.rotate = true;
        else if (a === '--rig') o.rigs.push(argv[++i]);
        else if (a === '--out') o.out = argv[++i];
        else if (a === '--json') o.json = argv[++i];
        else if (a === '--central') o.central = argv[++i];
        else if (a === '--help' || a === '-h') o.help = true;
        else { console.error(`unknown argument: ${a}`); process.exit(2); }
    }
    return o;
}

const newToken = () => crypto.randomBytes(32).toString('hex');

function envFragment(rigId, token, centralUrl) {
    return [
        `# Edge sync credentials for ${rigId} — generated by provision-rigs.js`,
        '# Append to the rig-edge node\'s .env, then restart its backend.',
        '# Treat as a secret: this token authorises telemetry writes as this rig.',
        `DEVICE_ID=${rigId}`,
        `DEVICE_TOKEN=${token}`,
        `CENTRAL_URL=${centralUrl}`,
        'SYNC_ENABLED=true',
        '',
    ].join('\n');
}

async function main() {
    const opts = parseArgs(process.argv);
    if (opts.help) {
        console.log(fs.readFileSync(__filename, 'utf8')
            .split('\n').filter((l) => l.startsWith('//')).join('\n'));
        return;
    }
    const centralUrl = opts.central || process.env.CENTRAL_URL
        || `http://${process.env.CENTRAL_HOST || 'crmf-backend'}:${process.env.INGEST_PORT || 6000}`;

    const where = opts.rigs.length ? 'WHERE rig_id = ANY($1)' : '';
    const params = opts.rigs.length ? [opts.rigs] : [];
    const { rows } = await query(
        `SELECT rig_id, name, device_token FROM rigs ${where} ORDER BY rig_id`, params);

    if (!rows.length) {
        console.error(opts.rigs.length
            ? `no matching rigs: ${opts.rigs.join(', ')}`
            : 'no rigs in the registry — seed the fleet first');
        process.exitCode = 1;
        return;
    }

    const targets = rows.filter((r) => opts.rotate || !r.device_token);
    const skipped = rows.length - targets.length;

    console.log(`${rows.length} rig(s) in scope; ${targets.length} to provision, ${skipped} already have a token${opts.rotate ? '' : ' (use --rotate to re-issue)'}`);
    if (!opts.apply) console.log('DRY RUN — re-run with --apply to write tokens\n');

    if (opts.out && opts.apply) fs.mkdirSync(opts.out, { recursive: true });

    let done = 0;
    const issued = {};   // rigId -> token, for --json
    for (const rig of targets) {
        const token = newToken();
        issued[rig.rig_id] = token;
        if (opts.apply) {
            await query('UPDATE rigs SET device_token = $1 WHERE rig_id = $2', [token, rig.rig_id]);
            await query(
                'INSERT INTO audit_log (actor, action, target, detail) VALUES ($1,$2,$3,$4)',
                ['provision-rigs', rig.device_token ? 'rig.rotate_token' : 'rig.provision_token',
                    rig.rig_id, { rotated: Boolean(rig.device_token), via: 'provision-rigs.js' }]
            ).catch(() => {});
            if (opts.out) {
                fs.writeFileSync(path.join(opts.out, `${rig.rig_id}.env`),
                    envFragment(rig.rig_id, token, centralUrl), { mode: 0o600 });
            }
            done++;
            // Print once — the token is not retrievable from the API afterwards.
            console.log(`  ${rig.rig_id}  ${token}`);
        } else {
            console.log(`  ${rig.rig_id}  (would ${rig.device_token ? 'rotate' : 'issue'})`);
        }
    }

    if (opts.apply && opts.json) {
        // Merge with any existing map so a partial (--rig) run doesn't drop the
        // credentials of rigs it didn't touch.
        let prev = {};
        try { prev = JSON.parse(fs.readFileSync(opts.json, 'utf8')); } catch { /* first run */ }
        fs.writeFileSync(opts.json, `${JSON.stringify({ ...prev, ...issued }, null, 2)}\n`, { mode: 0o600 });
    }

    if (opts.apply) {
        console.log(`\nprovisioned ${done} rig(s).`);
        if (opts.out) console.log(`edge .env fragments written to ${opts.out}`);
        if (opts.json) console.log(`per-rig token map written to ${opts.json}`);
        console.log('Copy each DEVICE_TOKEN to its rig-edge node and restart that backend.');
    }
}

main()
    .then(() => process.exit(process.exitCode || 0))
    .catch((e) => { console.error('provisioning failed:', e.message); process.exit(1); });
