apiVersion: v1
kind: ConfigMap
metadata:
  name: crmf-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "crmf.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
