{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "crmf.fullname" . }}-backend
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "crmf.backend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "crmf.backend.selectorLabels" . | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "crmf.fullname" . }}-frontend
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "crmf.frontend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "crmf.frontend.selectorLabels" . | nindent 6 }}
{{- end }}
